"""corregir tabla maquinas segun MER

Revision ID: b02d514ce2f7
Revises: 7a4d6e6d5a3b
Create Date: 2026-05-21 23:10:17.390626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02d514ce2f7'
down_revision: Union[str, None] = '7a4d6e6d5a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('disciplinas', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('evaluaciones_biometricas', 'observaciones',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maquinas', 'descripcion_tecnica',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('maquinas', 'estado_operativo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_index('ix_maquinas_codigo_serial', table_name='maquinas')
    op.drop_column('maquinas', 'codigo_serial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maquinas', sa.Column('codigo_serial', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index('ix_maquinas_codigo_serial', 'maquinas', ['codigo_serial'], unique=True)
    op.alter_column('maquinas', 'estado_operativo',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('maquinas', 'descripcion_tecnica',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('evaluaciones_biometricas', 'observaciones',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('disciplinas', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('disciplinas', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
