"""creacion inicial de todas las talblas

Revision ID: d7eba9fca6ea
Revises: 
Create Date: 2026-06-11 16:30:31.215387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7eba9fca6ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_maquinas_id'), 'categorias_maquinas', ['id'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_planes_suscripcion_id'), 'planes_suscripcion', ['id'], unique=False)
    op.create_table('productos_tienda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_tienda_id'), 'productos_tienda', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tecnica', sa.String(length=255), nullable=True),
    sa.Column('estado_operativo', sa.String(length=30), nullable=True),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('ultima_revision', sa.Date(), nullable=True),
    sa.Column('codigo_serial', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_maquinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_serial')
    )
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_clientes_cedula'), 'clientes', ['cedula'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('entrenadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_entrenadores_id'), 'entrenadores', ['id'], unique=False)
    op.create_table('tickets_mantenimiento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('descripcion_falla', sa.String(length=255), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('costo_reparacion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado_ticket', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_mantenimiento_id'), 'tickets_mantenimiento', ['id'], unique=False)
    op.create_table('control_accesos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('acceso_permitido', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_accesos_id'), 'control_accesos', ['id'], unique=False)
    op.create_table('evaluaciones_biometricas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estatura_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('porcentaje_grasa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_biometricas_id'), 'evaluaciones_biometricas', ['id'], unique=False)
    op.create_table('membresias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['planes_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresias_id'), 'membresias', ['id'], unique=False)
    op.create_table('sesiones_programadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cupo_maximo', sa.Integer(), nullable=False),
    sa.Column('cupos_ocupados', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_programadas_id'), 'sesiones_programadas', ['id'], unique=False)
    op.create_table('ventas_tienda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_tienda_id'), 'ventas_tienda', ['id'], unique=False)
    op.create_table('detalle_ventas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos_tienda.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas_tienda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_ventas_id'), 'detalle_ventas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=False),
    sa.Column('referencia_externa', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_programadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_detalle_ventas_id'), table_name='detalle_ventas')
    op.drop_table('detalle_ventas')
    op.drop_index(op.f('ix_ventas_tienda_id'), table_name='ventas_tienda')
    op.drop_table('ventas_tienda')
    op.drop_index(op.f('ix_sesiones_programadas_id'), table_name='sesiones_programadas')
    op.drop_table('sesiones_programadas')
    op.drop_index(op.f('ix_membresias_id'), table_name='membresias')
    op.drop_table('membresias')
    op.drop_index(op.f('ix_evaluaciones_biometricas_id'), table_name='evaluaciones_biometricas')
    op.drop_table('evaluaciones_biometricas')
    op.drop_index(op.f('ix_control_accesos_id'), table_name='control_accesos')
    op.drop_table('control_accesos')
    op.drop_index(op.f('ix_tickets_mantenimiento_id'), table_name='tickets_mantenimiento')
    op.drop_table('tickets_mantenimiento')
    op.drop_index(op.f('ix_entrenadores_id'), table_name='entrenadores')
    op.drop_table('entrenadores')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cedula'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_productos_tienda_id'), table_name='productos_tienda')
    op.drop_table('productos_tienda')
    op.drop_index(op.f('ix_planes_suscripcion_id'), table_name='planes_suscripcion')
    op.drop_table('planes_suscripcion')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_categorias_maquinas_id'), table_name='categorias_maquinas')
    op.drop_table('categorias_maquinas')
    # ### end Alembic commands ###
